version: "3.8"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql1
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: admin
    volumes:
      - ./:/code
    depends_on:
      - mysql1
    stdin_open: true
    tty: true
  mysql1:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    container_name: db1
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - .:/var/lib/mainsql
    stdin_open: true
    tty: true
volumes:
  db:
    driver: local
